### ISSUE TITLE
could you also show the position of softNMS and variance-voting?

### ISSUE THREAD

**Issue by JoyHuYY1412** [yihui-he/KL-Loss#10]

**Comment by sunycl** [comment]
I also can‘t find the position of softNMS and variance-voting. have anyone known that?

**Comment by sunycl** [comment]
oh, this is in KL-Loss/detectron/utils/cython_nms.pyx

**Comment by ethanhe42** [comment]
https://github.com/yihui-he/KL-Loss/blob/master/detectron/core/test.py#L68
