### ISSUE TITLE
What do the bbox_pred and bbox_targets mean?

### ISSUE THREAD

**Issue by JoyHuYY1412** [yihui-he/KL-Loss#11]
What do the bbox_pred and bbox_targets mean?

https://github.com/yihui-he/KL-Loss/blob/0a5617f02b5c0ebc57ddedffeb212859f1b3f008/detectron/modeling/fast_rcnn_heads.py#L114

In original bbox regression, the smooth L1 loss is calculated between the offsets, but according to your paper, I think here the 'bbox_pred' is the xyxy coordinates after regression? Can you explain it?

**Comment by ethanhe42** [comment]
they are still offsets. predicting `xyxy` are just the same as predicting `xy` in `xywh` setting
