### ISSUE TITLE
KL-Loss very large

### ISSUE THREAD

**Issue by EternityZY** [yihui-he/KL-Loss#13]
The kl-loss has three parts :bbox_pred_std_abs_mulw_loss,  bbox_pred_std_abs_logw_loss,loss_bbox. 

When I add it, bbox_pred_std_abs_logw_loss will be a very large negative number, resulting in a final loss=nan. If only loss_bbox is optimized, then log_loss will become a very large positive number, making the final loss_bbox almost zero. How to calculate kl-loss I can reproduce in the code, but how can you train me in the end, can you help me?

**Comment by ethanhe42** [comment]
All three parts are needed in training, u cannot just optimize `loss_bbox`. `bbox_pred_std_abs_mulw_loss, bbox_pred_std_abs_logw_loss` produces gradients for std, `loss_bbox` produces gradients for bbox.
Are u training on ur own dataset or COCO?
If u train on COCO as the README suggests https://github.com/yihui-he/KL-Loss#training , u will get the same results as in the paper. 
If u train on ur own dataset, there's nothing I can help.

**Comment by EternityZY** [comment]
Thanks for your reply, I am training COCO + YOLOv3, now bbox_pred_std_abs_logw_loss is a very small negative number, and it will get smaller and smaller.
Is these three items simple to add?

**Comment by ethanhe42** [comment]
yes, but as I said, bbox_pred_std_abs_mulw_loss, bbox_pred_std_abs_logw_loss produces gradients for std, loss_bbox produces gradients for bbox.

**Comment by csu-qwjy** [comment]
but, bbox_pred_std_abs_mulw_loss gradients will also go to bbox and std, because of  bbox_pred_std_abs_mulw_loss=bbox_pred_std_abs*('bbox_pred'- 'bbox_targets'),  resulting in a final loss=nan

**Comment by ethanhe42** [comment]
@csu-xiewei No, stopgradient prevents gradient goes to bbox

https://github.com/yihui-he/KL-Loss/blob/9242d088860c1d9990bbfb414f0800e7488b37c8/detectron/modeling/fast_rcnn_heads.py#L136
