### ISSUE TITLE
KL

### ISSUE THREAD

**Issue by github-luffy** [yihui-he/KL-Loss#14]
能具体解析一下下面的代码嘛，谢谢

**Comment by github-luffy** [comment]
能具体解析一下KL_loss的代码嘛，谢谢

**Comment by lg12170226** [comment]
fast_rcnn_heads.py->def add_fast_rcnn_losses(model)->if cfg.PRED_STD为KL_Loss的代码，对照论文上公式9和公式10推导

**Comment by ethanhe42** [comment]
the above comment answered the question. 
Besides, `bbox_pred_std_abs_mulw_loss, bbox_pred_std_abs_logw_loss` produces gradients for std, `loss_bbox` produces gradients for bbox
