### ISSUE TITLE
the loss_bbox is 0

### ISSUE THREAD

**Issue by lg12170226** [yihui-he/KL-Loss#15]
when I try to train on my data,the yaml is e2e_faster_rcnn_R-50-FPN_2x.yaml,used pre-model.But the loss_bbox is 0!
my class is 13+1,so modify  the net.py:
```python
for blob in model.params:
        '''
        unscoped_param_names[c2_utils.UnscopeName(str(blob))] = True
        '''
        keyname = c2_utils.UnscopeName(str(blob))
        if (keyname == 'cls_score_w' or keyname == 'cls_score_b' or keyname == 'bbox_pred_w' or keyname == 'bbox_pred_b'):
            continue
        unscoped_param_names[keyname] = True
```

the log is:
`{"accuracy_cls": "1.000000", "bbox_pred_std_abs_logw_loss": "0.000000", "bbox_pred_std_abs_mulw_loss": "0.000000", "eta": "0:00:41", "iter": 89920, "loss": "0.005503", "loss_bbox": "0.000000", "loss_cls": "0.000000", "loss_rpn_bbox_fpn2": "0.000000", "loss_rpn_bbox_fpn3": "0.000959", "loss_rpn_bbox_fpn4": "0.000380", "loss_rpn_bbox_fpn5": "0.000077", "loss_rpn_bbox_fpn6": "0.000000", "loss_rpn_cls_fpn2": "0.000117", "loss_rpn_cls_fpn3": "0.000207", "loss_rpn_cls_fpn4": "0.000185", "loss_rpn_cls_fpn5": "0.000018", "loss_rpn_cls_fpn6": "0.000000", "lr": "0.000100", "mb_qsize": 64, "mem": 13183, "time": "0.515552"}`

Is there something wrong?

**Comment by ethanhe42** [comment]
Did u modify `NUM_CLASSES` in config file?
Did ur dataset work on standard Detectron code?

**Comment by lg12170226** [comment]
@yihui-he yes, i modified `NUM_CLASSES`=14 in e2e_faster_rcnn_R-50-FPN_2x.yaml, and used mydata training in retinanet of standard Detectron ,it's ok
