### ISSUE TITLE
p_i in Eq.11 doesn't included in the code?

### ISSUE THREAD

**Issue by AppleBunnyy** [yihui-he/KL-Loss#16]
Hi, I'm trying to reproduce your paper on tensorflow.
Seems that p_i=exp(-(1-iou)^2/sigma) in Eq.11 doesn't included in the code? Or did I miss something..?
[https://github.com/yihui-he/softer-NMS/blob/master/detectron/utils/py_cpu_nms.py#L47](url)

`ovr_bbox = np.where((ious[i, :N] > thresh))[0]`
`avg_std_bbox = (dets[ovr_bbox, :4] / confidence[ovr_bbox]).sum(0) / (1/confidence[ovr_bbox]).sum(0)`

3q!!

**Comment by ethanhe42** [comment]
https://github.com/yihui-he/KL-Loss/blob/master/detectron/utils/py_cpu_nms.py#L51-L54
