### ISSUE TITLE
What to do with bounding box regression variance typically used when normalizing bounding box targets

### ISSUE THREAD

**Issue by JappaB** [yihui-he/KL-Loss#19]
Hi @yihui-he,
As Faster-RCNN normally uses the cx, cy, w, h encoding of bounding boxes and for this work you used the x1, y1, x2, y2 encoding, I was wondering the following:

What to do with bounding box regression variance typically used when normalizing bounding box targets?

In bounding box regression, there is typically in the implementation (not in the papers) a 'variance' with which the difference in bounding boxes are normalized (Good explanation of what I mean: https://leimao.github.io/blog/Bounding-Box-Encoding-Decoding/). E.g. in the detectron code:

https://github.com/yihui-he/KL-Loss/blob/962a687c7caca56b3b8562b437a8370077a59074/detectron/core/config.py#L456-L458 

(even though I believe that in the original implementation of Faster RCNN these values were (0.1, 0.1, 0.2, 0.2))

But where you transform the encoding from cx, cy, w, y into x1,y1,x2,y2; have you taken the variances into account as well while doing this or could you skip this? I think these variances are a bit of 'magical' values that get transported from implementation to implementation, without too many people questioning them. But I would love your take on these values.

**Comment by ethanhe42** [comment]
the first two variances `(10., 10.,` were used for `x1, y1, x2, y2`
https://github.com/yihui-he/KL-Loss/blob/1c67310c9f5a79cfa985fea241791ccedbdb7dcf/detectron/utils/boxes.py#L328-L353

`(10., 10., 5., 5.)`  is just the inverse of `(0.1, 0.1, 0.2, 0.2)`.

**Comment by JappaB** [comment]
Thanks a lot!
