### ISSUE TITLE
Sorry,How to add the KL-LOSS to faster-rcnn?I only find the fast-rcnn version

### ISSUE THREAD

**Issue by LittleBoy7** [yihui-he/KL-Loss#22]
Sorry,How to add the KL-LOSS to the faster-rcnn? I only find the fast-rcnn version。

**Comment by ethanhe42** [comment]
the demo in the [readme](https://github.com/yihui-he/KL-Loss#testing) is on faster-rcnn.

**Comment by LittleBoy7** [comment]
@yihui-he OK,thank you 。But Why are the loss bbox_pred_std_abs_mulw_loss not multiplied by bbox_outside_weights and the loss bbox_pred_std_abs_logw_loss not multiplied by bbox_inside_weights 
? I can't understand it...

**Comment by ethanhe42** [comment]
@LittleBoy7 you can refer to #18
