### ISSUE TITLE
Questions about pre-trained weights

### ISSUE THREAD

**Issue by JamesHao-ml** [yihui-he/KL-Loss#24]
Thanks for open sourcing the KL-loss. I have some questions with regard to training schemes. From configs/e2e_faster_rcnn_R-50-FPN_2x.yaml the pre-trained weights are based on MSCOCO rather than ImageNet. So the total training scheme is 4x? It seems that training more iterations will increase the mAP(1.2 ~ 1.3 points from 1x to 2x) on COCO. But I am not sure about the improvement from 2x to 4x. I wonder do you have comparision with 4x normal training without KL-Loss? Thanks.

**Comment by ethanhe42** [comment]
I tried 2x training with 2x weights as initialization a long time ago. IIRC the improvement was very marginal (~0.3).
