### ISSUE TITLE
KL-loss seems could be negative?

### ISSUE THREAD

**Issue by memoiry** [yihui-he/KL-Loss#3]
Hi, thanks for open sourcing the code.

I see from the code `model.net.Copy('bbox_pred_std', 'bbox_pred_std_abs')`, you just copy the log(sigma^2) as std instead of relu or sigmoid, then the (log(sigma^2))/2 could be negative in my understanding? which may cause the reg_log negative. Could that be a problem? 

Thanks!

**Comment by ethanhe42** [comment]
Yes, the loss can be negative because of the log term. That's not a problem.
