### ISSUE TITLE
How to output Box and Box std?

### ISSUE THREAD

**Issue by Chao86** [yihui-he/KL-Loss#33]
hello， @yihui-he ，I'm reading your paper,  confused about the way of model outputting Box and Box std. As figure 3 shows in you paper, 
![捕获](https://user-images.githubusercontent.com/44365146/135038404-f573d7cd-8ef0-44d3-acca-30d56f8ccd45.PNG)
Is the Box std generated by adding another fully connected layer in the model?  Beyond that,  have you added dropout operation in you model to produce uncertainty?
thanks in advance.

**Comment by ethanhe42** [comment]
Is the Box std generated by adding another fully connected layer in the model? yes
added dropout operation in you model to produce uncertainty? no
