### ISSUE TITLE
Extra term in the KL-loss code and the NaN problem

### ISSUE THREAD

**Issue by huiqu18** [yihui-he/KL-Loss#4]
Hi, thanks for the source code. 

Could you please explain the aim of adding the term ```0.5 * sq2 * exp(-a) * beta``` in the loss function? 
```
if (abs_val < beta) {
    out[ind] = (sq2 * exp(-a) * 0.5 * val * val / beta + 0.5 * sq2 * exp(-a) * beta + a) / max(S[0], 1.0);
} else {
    out[ind] = (sq2 * exp(-a) * (abs_val - 0.5 * beta) + 0.5 * sq2 * exp(-a) * beta + a) / max(S[0], 1.0);
}
```

Besides, in the case that the variance is close to zero while the regression error (```abs_val``` in the code) is relatively large (probably happens in the first iteration due to initialization), the loss is extremely large and will result in NaN. Did you encounter this problem? If yes, how to solve it?

Thanks!

**Comment by ethanhe42** [comment]
These are experimental codes that are actually not used. Please refer to https://github.com/yihui-he/KL-Loss/blob/master/detectron/modeling/fast_rcnn_heads.py

**Comment by AppleBunnyy** [comment]
I encontered same problem @huiqu18 mentioned on other dataset. Loss is NAN due to extremely large or small \alpha term in exp(-\alpha) in KL-Loss. I clip \alpha value in (-50,50), but losses are very still high. Is there any way to fix it?
