### ISSUE TITLE
Code location of KL-Loss

### ISSUE THREAD

**Issue by DCNSW** [yihui-he/KL-Loss#5]
I can't find definition or usage of KL-Loss function in code, also, I cannot find code which presents in Issues [2](https://github.com/yihui-he/KL-Loss/issues/2). @yihui-he, @dh562231640, was I missing something? Or I didn't understand your idea and code implement correctly. Thank you for your answer.

**Comment by ethanhe42** [comment]
https://github.com/yihui-he/KL-Loss/blob/master/detectron/modeling/fast_rcnn_heads.py#L110

**Comment by JoyHuYY1412** [comment]
> https://github.com/yihui-he/KL-Loss/blob/master/detectron/modeling/fast_rcnn_heads.py#L110

could you also show the position of softNMS and variance-voting? thanks >.<
