### ISSUE TITLE
what do the 'bbox_inside_weights' and 'bbox_outside_weights' mean?

### ISSUE THREAD

**Issue by JoyHuYY1412** [yihui-he/KL-Loss#7]
Sorry but I am not familiar with Caffe2. Could you please tell me what do the 'bbox_inside_weights' and 'bbox_outside_weights' mean in https://github.com/yihui-he/KL-Loss/blob/0a5617f02b5c0ebc57ddedffeb212859f1b3f008/detectron/modeling/fast_rcnn_heads.py#L116?
And the `loss_box` here https://github.com/yihui-he/KL-Loss/blob/0a5617f02b5c0ebc57ddedffeb212859f1b3f008/detectron/modeling/fast_rcnn_heads.py#L154 represent which part of loss? Why would you set the `bbox_outside_weights` like this?

**Comment by JoyHuYY1412** [comment]
I don't know if I understand it correct:
So for bbox regression, you have three part of loss: loss_bbox, bbox_pred_std_abs_mulw_loss and bbox_pred_std_abs_logw_loss.
The latter two losses are the KL-loss form you proposed in your paper.
Does the loss_box the same as original bbox regression loss? Do you use this loss in order to train for the prediction of box coordinates, since you `StopGradient` this part when calculate KL-loss. And the KL-loss is just used to train the `alpha` in your network. 
The `bbox_outside_weights` of  `loss_box` are also exp(-alpha) in order to keep the balance with KL-loss?
Am I right?

**Comment by ethanhe42** [comment]
Yes
