### ISSUE TITLE
why scale = -0.5 in model.net.Scale('bbox_pred_std_abs_log_', 'bbox_pred_std_abs_log', scale=-0.5*model.GetLossScale())

### ISSUE THREAD

**Issue by gfjiangly** [yihui-he/KL-Loss#9]
https://github.com/yihui-he/KL-Loss/blob/0a5617f02b5c0ebc57ddedffeb212859f1b3f008/detectron/modeling/fast_rcnn_heads.py#L138-L149

it seems be scale=0.5 in model.net.Scale('bbox_pred_std_abs_log_', 'bbox_pred_std_abs_log', scale=-0.5*model.GetLossScale()), then bbox_pred_std_abs_log=0.5 * log(sigma^2).
This is the same as the if cfg.PRED_STD_LOG branch above.

BTW, the else branch does not seem to get bbox_inws_out = e^{-alpha} * smooth_l1

**Comment by ethanhe42** [comment]
The else branch is for some experiments not related to this paper
